version: "3"

services:
  mongo:
    container_name: in-season-mongodb
    image: mongo
    restart: always
    env_file: ./.env
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - in-season-mongodb:/data/db
    networks:
      - backend

  in-season-backend:
    container_name: in-season-backend
    image: jasonherngwang/in-season-backend:1.0
    platform: linux/amd64
    depends_on:
      - mongo
    build: ../in-season-backend
    restart: always
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=in-season-mongodb
      - MONGO_USER=$MONGO_USER
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_DB_NAME=in-season
      - MONGO_PORT=27017
    networks:
      - backend
      - frontend

  in-season-frontend:
    container_name: in-season-frontend
    image: jasonherngwang/in-season-frontend:1.0
    platform: linux/amd64
    depends_on:
      - in-season-backend
    build:
      context: ../in-season-frontend
      args:
        - VITE_API_BASE_URL=$VITE_API_BASE_URL
    ports:
      - "8888:80"
    networks:
      - frontend

volumes:
  in-season-mongodb:

networks:
  backend:
  frontend:
